/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculadora;

import View.Interface;
import javax.swing.SwingUtilities;

public class App {

    public static void main(String[] args) {
        
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Interface tela = new Interface();
            }
        });
    }
}
